export const SITE_COPY = Object.freeze({
  brand: 'DSM 학습 지도',
  nav: Object.freeze([
    '프로젝트 지도',
    '아키텍처',
    '개념',
    '기능 흐름',
    '파일',
    '연습',
  ]),
  searchHint: '파일·클래스·함수 검색',
  scope: '124개 파일 · 13,168줄 · 오프라인',
  cta: 'Task 흐름 학습 시작',
  sourceLabel: '원본 코드 · 변경 없음',
  explanationLabel: 'AI 설명 · 원본 밖',
});

export const PILOT_A_FLOW = Object.freeze({
  title: 'Task 변경 → 점수 재계산 + 알림 예약 상태 동기화',
  transaction: Object.freeze({
    owner: 'TasksService',
    method: 'Prisma.$transaction',
    isolation: 'Serializable',
    retry: 'P2034 충돌 시 전체 callback을 최대 두 번 재시도',
  }),
  nodes: Object.freeze([
    { id: 'request', label: 'PATCH /tasks/:id', group: 'http' },
    { id: 'tasks-controller', label: 'TasksController.update()', group: 'http' },
    { id: 'tasks-service', label: 'TasksService.update()', group: 'domain' },
    { id: 'transaction', label: 'Prisma.$transaction', group: 'transaction' },
    { id: 'task', label: 'Task update', group: 'data' },
    { id: 'schedule', label: 'NotificationSchedule', group: 'data' },
    { id: 'delivery', label: 'NotificationDelivery', group: 'data' },
    { id: 'scores-service', label: 'ScoresService.recompute()', group: 'domain' },
    { id: 'daily-score', label: 'DailyScore upsert', group: 'data' },
    { id: 'user', label: 'User totalScore/tier', group: 'data' },
    { id: 'prisma', label: 'Prisma', group: 'persistence' },
    { id: 'postgresql', label: 'PostgreSQL', group: 'persistence' },
  ]),
  edges: Object.freeze([
    { from: 'request', to: 'tasks-controller', state: 'confirmed', label: 'route' },
    { from: 'tasks-controller', to: 'tasks-service', state: 'confirmed', label: '호출' },
    { from: 'tasks-service', to: 'transaction', state: 'confirmed', label: 'Serializable' },
    { from: 'transaction', to: 'task', state: 'confirmed', label: '항상' },
    { from: 'transaction', to: 'schedule', state: 'conditional', label: '일정 변경 시 cancel/create' },
    { from: 'transaction', to: 'delivery', state: 'conditional', label: 'nonterminal delivery 존재 시 cancel' },
    { from: 'transaction', to: 'scores-service', state: 'confirmed', label: '같은 transaction client' },
    { from: 'scores-service', to: 'daily-score', state: 'confirmed', label: 'UTC day upsert' },
    { from: 'scores-service', to: 'user', state: 'confirmed', label: '합계·tier 갱신' },
    { from: 'task', to: 'prisma', state: 'confirmed', label: 'client write' },
    { from: 'daily-score', to: 'prisma', state: 'confirmed', label: 'client write' },
    { from: 'user', to: 'prisma', state: 'confirmed', label: 'client write' },
    { from: 'prisma', to: 'postgresql', state: 'confirmed', label: 'persistence' },
  ]),
  comparison: Object.freeze({
    title: 'NotificationsService는 별도 경계',
    text: 'FCM token register/revoke를 담당하며 Task mutation의 직접 호출 경로가 아니다. 실제 FCM 발송은 Pilot A 범위 밖이다.',
  }),
});

export const PILOT_EXERCISES = Object.freeze([
  {
    id: 'flow-order',
    type: 'sequence',
    difficulty: '입문',
    question: 'PATCH 요청부터 PostgreSQL 반영까지 확인된 순서를 배열하세요.',
    answer: 'TasksController.update → TasksService.update → Serializable transaction → Task·조건부 schedule/delivery·score 변경 → Prisma → PostgreSQL 순서다.',
    sourcePaths: ['DSM_Back/src/tasks/tasks.controller.ts', 'DSM_Back/src/tasks/tasks.service.ts'],
  },
  {
    id: 'controller-service',
    type: 'responsibility',
    difficulty: '입문',
    question: 'controller와 service가 각각 책임지는 일을 구분하세요.',
    answer: 'controller는 인증 사용자와 DTO를 service에 넘기고, service는 소유권·transaction·side effect를 조율한다.',
    sourcePaths: ['DSM_Back/src/tasks/tasks.controller.ts', 'DSM_Back/src/tasks/tasks.service.ts'],
  },
  {
    id: 'transaction-boundary',
    type: 'transaction',
    difficulty: '주니어',
    question: 'Task, 예약 상태, 점수 중 같은 transaction client를 사용하는 작업을 찾으세요.',
    answer: 'Task write, 조건부 schedule/delivery update, ScoresService.recompute가 같은 Serializable callback 안에서 같은 client를 사용한다.',
    sourcePaths: ['DSM_Back/src/tasks/tasks.service.ts', 'DSM_Back/src/scores/scores.service.ts'],
  },
  {
    id: 'schedule-prediction',
    type: 'prediction',
    difficulty: '주니어',
    question: '과거 시각으로 startAt을 바꾸면 새 PENDING schedule이 생기는지 예측하세요.',
    answer: '기존 nonterminal 상태는 취소하지만 새 일정이 미래가 아니므로 새 schedule은 만들지 않는다.',
    sourcePaths: ['DSM_Back/src/tasks/tasks.service.ts', 'DSM_Back/src/tasks/tasks.service.spec.ts'],
  },
  {
    id: 'score-policy',
    type: 'policy',
    difficulty: '주니어',
    question: '완료율과 난이도가 일일 점수에 반영되는 근거를 찾으세요.',
    answer: 'DIFFICULTY_SCORE 합계에 achievementMultiplier를 적용하고 DAILY_SCORE_CAP 900으로 제한한다.',
    sourcePaths: ['DSM_Back/src/scores/scores.policy.ts', 'DSM_Back/src/scores/scores.service.spec.ts'],
  },
  {
    id: 'test-evidence',
    type: 'evidence',
    difficulty: '주니어',
    question: 'unit test와 현재 e2e test가 각각 보장하는 범위를 구분하세요.',
    answer: 'service spec은 transaction·조건 분기를 검증하지만 e2e spec은 health와 404 envelope만 검증하므로 Task 전체 흐름의 e2e 증거는 아니다.',
    sourcePaths: ['DSM_Back/src/tasks/tasks.service.spec.ts', 'DSM_Back/test/app.e2e-spec.ts'],
  },
  {
    id: 'remove-false-edge',
    type: 'diagram-fix',
    difficulty: '주니어',
    question: 'TasksService → NotificationsService → FCM send로 그린 선을 어떻게 고쳐야 하나요?',
    answer: '그 직접 호출선을 삭제하고 transaction에서 Prisma로 NotificationSchedule/NotificationDelivery를 직접 변경하는 조건부 선을 그린다. FCM send는 범위 밖으로 둔다.',
    sourcePaths: ['DSM_Back/src/tasks/tasks.service.ts', 'DSM_Back/src/notifications/notifications.service.ts'],
  },
]);

function freezeGuide(guide) {
  return Object.freeze({
    ...guide,
    focus: Object.freeze(guide.focus),
    evidence: Object.freeze(guide.evidence.map((item) => Object.freeze(item))),
    risks: Object.freeze(guide.risks),
    related: Object.freeze(guide.related),
    exercises: Object.freeze(guide.exercises),
  });
}

export const FILE_GUIDES = Object.freeze({
  'DSM_Back/src/app.module.ts': freezeGuide({
    classification: 'core',
    role: 'Nest 애플리케이션의 composition root로 전역 설정과 기능 모듈을 조립한다.',
    focus: ['ConfigModule 환경 검증', 'ScheduleModule 초기화', 'Prisma·Tasks·Scores·Notifications 모듈 경계'],
    childExplanation: '학교 시간표에 어떤 반과 과목이 있는지 한 장에 등록하는 교무실 명단과 같다.',
    juniorExplanation: 'AppModule은 기능 구현을 직접 수행하지 않고 Nest DI graph의 시작점을 만든다. TasksModule과 NotificationsModule이 함께 import되어도 두 service가 직접 호출된다는 뜻은 아니다.',
    evidence: [{ path: 'DSM_Back/src/app.module.ts', symbol: 'AppModule', claim: 'module imports' }],
    risks: ['module import 관계를 runtime call 관계로 오해하지 않는다.'],
    related: ['DSM_Back/src/tasks/tasks.service.ts', 'DSM_Back/src/notifications/notifications.service.ts'],
    exercises: ['controller-service'],
  }),
  'DSM_Back/prisma/schema.prisma': freezeGuide({
    classification: 'core',
    role: 'Task, 점수, 알림 예약·전달과 User 관계를 정의하는 persistence 계약이다.',
    focus: ['Task 관계와 status', 'DailyScore 복합 고유키', 'NotificationSchedule·NotificationDelivery 연결', 'User aggregate fields'],
    childExplanation: '데이터가 들어갈 서랍의 이름과 서로 연결되는 열쇠를 미리 그린 설계도다.',
    juniorExplanation: 'service의 Prisma 호출이 어떤 row와 관계를 변경할 수 있는지는 schema model과 relation이 결정한다. schema는 호출 순서를 증명하지 않으므로 service 근거와 함께 읽는다.',
    evidence: [{ path: 'DSM_Back/prisma/schema.prisma', symbol: 'Task', claim: 'persistence model' }],
    risks: ['model 관계만 보고 transaction 원자성을 단정할 수 없다.'],
    related: ['DSM_Back/src/tasks/tasks.service.ts', 'DSM_Back/src/scores/scores.service.ts'],
    exercises: ['transaction-boundary'],
  }),
  'DSM_Back/src/tasks/tasks.controller.ts': freezeGuide({
    classification: 'core',
    role: '인증된 HTTP Task 요청을 DTO와 사용자 ID로 바꾸어 TasksService에 전달한다.',
    focus: ['route decorator', 'req.user.sub', 'DTO validation boundary', 'service forwarding'],
    childExplanation: '접수 창구가 신청서와 학생 번호를 확인해 실제 처리 담당자에게 넘기는 역할이다.',
    juniorExplanation: 'controller는 URL·HTTP method·body 타입을 고정하고 인증 principal을 service 인자로 전달한다. transaction과 DB side effect는 controller 책임이 아니다.',
    evidence: [{ path: 'DSM_Back/src/tasks/tasks.controller.ts', symbol: 'update', claim: 'PATCH forwarding' }],
    risks: ['controller forwarding을 business rule 구현으로 과대평가하지 않는다.'],
    related: ['DSM_Back/src/tasks/dto/update-task.dto.ts', 'DSM_Back/src/tasks/tasks.service.ts'],
    exercises: ['flow-order', 'controller-service'],
  }),
  'DSM_Back/src/tasks/tasks.service.ts': freezeGuide({
    classification: 'core',
    role: '소유권 확인과 Task mutation, 조건부 알림 예약 상태, 점수 재계산을 하나의 transaction으로 조율한다.',
    focus: ['findOneWithClient 소유권 경계', 'Serializable P2034 retry', 'scheduleRelevantChange', 'nonterminal cancellation', 'recomputeDays'],
    childExplanation: '한 번의 수정표에 할 일, 알림표, 점수표를 함께 적고 전부 성공해야 도장을 찍는 담당자다.',
    juniorExplanation: 'create/update/remove/complete는 runSerializableTransaction을 사용한다. update는 기존 날짜와 새 날짜의 서로 다른 UTC day를 재계산하고, 일정 관련 입력이 바뀔 때만 예약·전달 상태를 취소하거나 새 예약을 만든다.',
    evidence: [
      { path: 'DSM_Back/src/tasks/tasks.service.ts', symbol: 'update', claim: 'mutation orchestration' },
      { path: 'DSM_Back/src/tasks/tasks.service.spec.ts', symbol: 'serializable transaction retry', claim: 'retry evidence' },
    ],
    risks: ['TasksService가 NotificationsService나 FCM send를 직접 호출한다고 그리면 사실과 다르다.', 'P2034 재시도는 callback 전체를 다시 실행한다.'],
    related: ['DSM_Back/src/tasks/tasks.controller.ts', 'DSM_Back/src/scores/scores.service.ts', 'DSM_Back/src/notifications/notification-schedule.constants.ts'],
    exercises: ['flow-order', 'transaction-boundary', 'schedule-prediction', 'remove-false-edge'],
  }),
  'DSM_Back/src/tasks/dto/create-task.dto.ts': freezeGuide({
    classification: 'support',
    role: 'Task 생성 요청에서 필수·선택 필드와 형식을 선언한다.',
    focus: ['title required', 'startAt/endAt date string', 'TaskDifficulty enum', 'optional categoryId', 'optional notificationEnabled'],
    childExplanation: '새 할 일을 만들 때 빠진 칸이나 잘못 적은 날짜가 없는지 확인하는 신청서다.',
    juniorExplanation: 'class-validator decorator가 HTTP body의 구조를 검증한다. notificationEnabled가 유효해도 실제 schedule 생성 조건은 TasksService가 현재 시각과 상태를 함께 판단한다.',
    evidence: [{ path: 'DSM_Back/src/tasks/dto/create-task.dto.ts', symbol: 'CreateTaskDto', claim: 'input contract' }],
    risks: ['DTO 유효성을 schedule 생성 보장으로 오해하지 않는다.'],
    related: ['DSM_Back/src/tasks/tasks.controller.ts', 'DSM_Back/src/tasks/tasks.service.ts'],
    exercises: ['controller-service'],
  }),
  'DSM_Back/src/tasks/dto/update-task.dto.ts': freezeGuide({
    classification: 'support',
    role: '부분 Task 수정에서 허용되는 선택 필드와 enum/date 형식을 선언한다.',
    focus: ['모든 필드 optional', 'TaskStatus enum', 'startAt/endAt changes', 'categoryId', 'notificationEnabled'],
    childExplanation: '바꾸고 싶은 칸만 적어 내는 수정 신청서다.',
    juniorExplanation: 'optional DTO이므로 누락 필드는 기존 Task 값으로 유지된다. service는 startAt, status, notificationEnabled의 실제 변화 여부를 계산해 schedule side effect를 결정한다.',
    evidence: [{ path: 'DSM_Back/src/tasks/dto/update-task.dto.ts', symbol: 'UpdateTaskDto', claim: 'partial update contract' }],
    risks: ['필드가 DTO에 있다는 사실만으로 DB update나 schedule side effect가 항상 발생하지 않는다.'],
    related: ['DSM_Back/src/tasks/tasks.controller.ts', 'DSM_Back/src/tasks/tasks.service.ts'],
    exercises: ['schedule-prediction'],
  }),
  'DSM_Back/src/scores/scores.policy.ts': freezeGuide({
    classification: 'core',
    role: '난이도, 완료율, 일일 cap과 누적 tier를 계산하는 순수 정책이다.',
    focus: ['DIFFICULTY_SCORE 10/20/30', 'achievementMultiplier', 'DAILY_SCORE_CAP 900', 'computeDailyScore', 'tierForScore'],
    childExplanation: '할 일 난이도와 완료 비율을 점수표 규칙에 넣어 계산하는 계산기다.',
    juniorExplanation: 'DB 없이 입력만으로 ScoreResult를 만든다. raw score에 완료율 multiplier를 적용하고 900 cap을 씌우며, 누적 점수는 내림차순 threshold로 tier를 고른다.',
    evidence: [{ path: 'DSM_Back/src/scores/scores.policy.ts', symbol: 'computeDailyScore', claim: 'pure policy' }],
    risks: ['policy 계산과 실제 저장 성공은 별도 관심사다.'],
    related: ['DSM_Back/src/scores/scores.service.ts', 'DSM_Back/src/scores/scores.service.spec.ts'],
    exercises: ['score-policy'],
  }),
  'DSM_Back/src/scores/scores.service.ts': freezeGuide({
    classification: 'core',
    role: 'UTC day의 Task를 읽어 점수를 계산하고 DailyScore와 User aggregate를 같은 client로 갱신한다.',
    focus: ['UTC day range', 'completed Task difficulties', 'DailyScore upsert', 'recomputeUserTotal', 'supplied transaction client'],
    childExplanation: '하루 숙제 기록을 모아 오늘 점수표와 전체 등급표를 함께 고치는 기록 담당자다.',
    juniorExplanation: 'recompute는 전달받은 Prisma transaction client로 Task 조회, DailyScore upsert, User totalScore/tier update를 수행한다. TasksService transaction 안에서 호출되면 같은 원자 경계에 참여한다.',
    evidence: [
      { path: 'DSM_Back/src/scores/scores.service.ts', symbol: 'recompute', claim: 'score persistence' },
      { path: 'DSM_Back/src/scores/scores.service.spec.ts', symbol: 'recompute', claim: 'transaction client evidence' },
    ],
    risks: ['UTC day 경계와 application local time을 섞지 않는다.'],
    related: ['DSM_Back/src/scores/scores.policy.ts', 'DSM_Back/src/tasks/tasks.service.ts'],
    exercises: ['transaction-boundary', 'score-policy'],
  }),
  'DSM_Back/src/notifications/notifications.service.ts': freezeGuide({
    classification: 'core',
    role: '인증 사용자 기준 FCM token 등록·갱신·재활성화·해제를 담당하는 별도 경계다.',
    focus: ['register', 'revoke', 'foreign owner conflict', 'revoked token reactivation', 'Serializable retry'],
    childExplanation: '할 일 알림 시간을 정하는 곳이 아니라, 어느 기기로 알림을 받을지 명찰을 등록하는 창구다.',
    juniorExplanation: '이 service는 FCM token lifecycle을 다룬다. TasksService의 일정 mutation은 이 service를 호출하지 않고 Prisma client로 schedule/delivery를 직접 변경한다.',
    evidence: [
      { path: 'DSM_Back/src/notifications/notifications.service.ts', symbol: 'register', claim: 'token lifecycle' },
      { path: 'DSM_Back/src/notifications/notifications.service.spec.ts', symbol: 'NotificationsService', claim: 'ownership evidence' },
    ],
    risks: ['Task mutation의 직접 의존성이나 실제 FCM send로 그리지 않는다.'],
    related: ['DSM_Back/src/notifications/notifications.service.spec.ts', 'DSM_Back/src/tasks/tasks.service.ts'],
    exercises: ['remove-false-edge'],
  }),
  'DSM_Back/src/notifications/notification-schedule.constants.ts': freezeGuide({
    classification: 'support',
    role: 'schedule/delivery 상태와 취소 대상 nonterminal 상태의 공통 어휘를 고정한다.',
    focus: ['schedule statuses', 'delivery UNKNOWN', 'PENDING/PROCESSING nonterminal set'],
    childExplanation: '알림표에 쓸 수 있는 상태 이름과 아직 끝나지 않은 상태를 정한 범례다.',
    juniorExplanation: 'TasksService는 이 상수로 취소 대상 상태를 제한한다. delivery에는 UNKNOWN이 있지만 nonterminal cancellation set은 PENDING과 PROCESSING이다.',
    evidence: [{ path: 'DSM_Back/src/notifications/notification-schedule.constants.ts', symbol: 'NotificationScheduleStatus', claim: 'status vocabulary' }],
    risks: ['FAILED·SENT·UNKNOWN까지 nonterminal로 간주하지 않는다.'],
    related: ['DSM_Back/src/tasks/tasks.service.ts', 'DSM_Back/prisma/schema.prisma'],
    exercises: ['schedule-prediction'],
  }),
  'DSM_Back/src/prisma/prisma.service.ts': freezeGuide({
    classification: 'support',
    role: 'Nest lifecycle에 PrismaClient 연결과 해제를 결합한다.',
    focus: ['PrismaClient inheritance', 'OnModuleInit', 'test-mode connect bypass', 'OnModuleDestroy'],
    childExplanation: '앱이 켜질 때 데이터 창고 문을 열고 끝날 때 닫는 열쇠 관리자다.',
    juniorExplanation: 'production runtime에서는 module init 때 connect하고 destroy 때 disconnect한다. NODE_ENV=test에서는 실제 연결을 건너뛰어 unit/e2e module 구성 시 불필요한 DB 접근을 막는다.',
    evidence: [{ path: 'DSM_Back/src/prisma/prisma.service.ts', symbol: 'PrismaService', claim: 'client lifecycle' }],
    risks: ['test-mode connect bypass가 실제 DB 동작 검증을 대신하지 않는다.'],
    related: ['DSM_Back/prisma/schema.prisma', 'DSM_Back/src/tasks/tasks.service.ts'],
    exercises: ['test-evidence'],
  }),
  'DSM_Back/src/tasks/tasks.service.spec.ts': freezeGuide({
    classification: 'core',
    role: 'Task service의 mutation, retry, ownership, schedule/delivery와 score side effect를 검증하는 unit evidence다.',
    focus: ['create schedule cases', 'P2034 bounded retry', 'update schedule relevance', 'distinct UTC days', 'nested write failure ordering'],
    childExplanation: '담당자가 규칙대로 처리하는지 여러 상황표를 넣어 확인하는 검사 기록이다.',
    juniorExplanation: 'spec은 Prisma double을 통해 service 분기와 호출 순서를 검증한다. 실제 PostgreSQL isolation과 delivery runtime을 실행하는 integration test는 아니다.',
    evidence: [{ path: 'DSM_Back/src/tasks/tasks.service.spec.ts', symbol: 'TasksService', claim: 'behavior tests' }],
    risks: ['mock 기반 unit 증거를 실제 DB·실제 FCM 증거로 확대하지 않는다.'],
    related: ['DSM_Back/src/tasks/tasks.service.ts', 'DSM_Back/test/app.e2e-spec.ts'],
    exercises: ['test-evidence', 'schedule-prediction'],
  }),
  'DSM_Back/src/scores/scores.service.spec.ts': freezeGuide({
    classification: 'core',
    role: '점수 계산 저장, cap, 빈 날, transaction client와 조회 동작을 검증한다.',
    focus: ['daily score persistence', '900 cap', 'empty day', 'supplied client routing', 'summary read'],
    childExplanation: '점수 담당자가 정상 날, 빈 날, 너무 큰 점수에서도 규칙대로 기록하는지 확인한 시험지다.',
    juniorExplanation: 'recompute가 전달된 client만 사용하고 DailyScore와 User aggregate를 갱신하는지를 검증한다. policy 자체의 경계는 policy spec과 함께 해석해야 한다.',
    evidence: [{ path: 'DSM_Back/src/scores/scores.service.spec.ts', symbol: 'ScoresService', claim: 'score evidence' }],
    risks: ['unit test의 고정 시각과 운영 시간대를 동일시하지 않는다.'],
    related: ['DSM_Back/src/scores/scores.service.ts', 'DSM_Back/src/scores/scores.policy.ts'],
    exercises: ['score-policy', 'test-evidence'],
  }),
  'DSM_Back/src/notifications/notifications.service.spec.ts': freezeGuide({
    classification: 'core',
    role: 'FCM token 등록·재등록·재활성화·소유권 충돌·해제·retry를 검증한다.',
    focus: ['same-user registration', 'revoked reactivation', 'foreign owner 409', 'P2034 retry limit', 'idempotent revoke'],
    childExplanation: '기기 명찰을 같은 학생이 다시 쓰는 경우와 다른 학생이 가져가려는 경우를 확인한 검사 기록이다.',
    juniorExplanation: 'token row lifecycle과 actor 경계를 검증하며 Task schedule mutation을 검증하지 않는다. 이 차이가 Pilot에서 잘못된 직접 호출선을 제거하는 근거다.',
    evidence: [{ path: 'DSM_Back/src/notifications/notifications.service.spec.ts', symbol: 'NotificationsService', claim: 'token ownership tests' }],
    risks: ['token 등록 성공을 알림 발송 성공으로 해석하지 않는다.'],
    related: ['DSM_Back/src/notifications/notifications.service.ts', 'DSM_Back/src/tasks/tasks.service.spec.ts'],
    exercises: ['remove-false-edge', 'test-evidence'],
  }),
  'DSM_Back/test/app.e2e-spec.ts': freezeGuide({
    classification: 'support',
    role: 'AppModule bootstrapping 뒤 health 응답과 404 error envelope를 HTTP 경계에서 확인한다.',
    focus: ['TestingModule AppModule import', 'configureApp', 'GET /health', '404 normalization'],
    childExplanation: '건물 문이 열리고 안내 데스크가 기본 질문과 없는 방 요청에 답하는지 확인하는 점검이다.',
    juniorExplanation: '현재 e2e suite는 health와 missing route만 호출한다. Task PATCH, score recompute, schedule sync의 end-to-end 성공을 증명하지 않는다.',
    evidence: [{ path: 'DSM_Back/test/app.e2e-spec.ts', symbol: 'AppController (e2e)', claim: 'HTTP smoke evidence' }],
    risks: ['현재 e2e test를 Pilot 전체 흐름의 통합 검증으로 표시하지 않는다.'],
    related: ['DSM_Back/src/app.module.ts', 'DSM_Back/src/tasks/tasks.service.spec.ts'],
    exercises: ['test-evidence'],
  }),
});
